language: java
jdk:
  - openjdk14
install:
  - sudo apt-get install -y ant ant-optional
services:
  - mysql
script: 
  - export JAVA_HOME=~/openjdk14
  - export JDK_HOME=~/openjdk14
  - ant all
sudo: required
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e 'CREATE DATABASE LAS2PEERMON;'
  - mysql -u root LAS2PEERMON < etc/create_database.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)
